<?php
if (!function_exists('alertSeverityClass')) { function alertSeverityClass(?string $severity): string { return match(strtolower((string)$severity)){ 'critical'=>'critical','high'=>'high','medium'=>'medium','low'=>'low',default=>'unknown' }; } }
if (!function_exists('alertSeverityLabel')) { function alertSeverityLabel(?string $severity): string { return match(strtolower(trim((string)$severity))){ 'critical'=>'Critical','high'=>'High','medium'=>'Medium','low'=>'Low',default=>'Unknown' }; } }
if (!function_exists('alertStatusClass')) { function alertStatusClass(?string $status): string { return strtolower((string)$status)==='archived'?'archived':'active'; } }
if (!function_exists('alertStatusLabel')) { function alertStatusLabel(?string $status): string { return strtolower(trim((string)$status))==='archived'?'Archived':'Active'; } }
if (!function_exists('fetchAlertCategories')) { function fetchAlertCategories(PDO $pdo): array { $s=$pdo->query("SELECT DISTINCT category FROM alerts WHERE category IS NOT NULL AND category<>'' ORDER BY category ASC"); return $s->fetchAll(PDO::FETCH_COLUMN); } }
if (!function_exists('fetchAlertLocations')) { function fetchAlertLocations(PDO $pdo): array { $s=$pdo->query("SELECT DISTINCT location FROM alerts WHERE location IS NOT NULL AND location<>'' ORDER BY location ASC"); return $s->fetchAll(PDO::FETCH_COLUMN); } }
if (!function_exists('fetchAlertSources')) { function fetchAlertSources(PDO $pdo): array { $s=$pdo->query("SELECT id,name FROM sources ORDER BY name ASC"); return $s->fetchAll(PDO::FETCH_ASSOC); } }
if (!function_exists('getAlertById')) { function getAlertById(PDO $pdo,int $id): ?array { $s=$pdo->prepare("SELECT a.id,a.source_id,a.external_id,a.title,a.description,a.category,a.location,a.severity,a.published_at,a.source_url,a.status,a.created_at,a.updated_at,s.name AS source_name,s.source_type FROM alerts a LEFT JOIN sources s ON s.id=a.source_id WHERE a.id=? LIMIT 1"); $s->execute([$id]); $r=$s->fetch(PDO::FETCH_ASSOC); return $r?:null; } }
if (!function_exists('buildAlertSearchWhere')) { function buildAlertSearchWhere(array $filters,array &$params): string { $w=['1=1']; if(!empty($filters['q'])){$w[]='(a.title LIKE :q OR a.description LIKE :q OR a.location LIKE :q)';$params[':q']='%'.trim($filters['q']).'%';} if(!empty($filters['category'])){$w[]='a.category=:category';$params[':category']=$filters['category'];} if(!empty($filters['location'])){$w[]='a.location LIKE :location';$params[':location']='%'.trim($filters['location']).'%';} if(!empty($filters['severity'])){$w[]='a.severity=:severity';$params[':severity']=$filters['severity'];} if(!empty($filters['status'])){$w[]='a.status=:status';$params[':status']=$filters['status'];} if(!empty($filters['source_id'])&&ctype_digit((string)$filters['source_id'])){$w[]='a.source_id=:source_id';$params[':source_id']=(int)$filters['source_id'];} return implode(' AND ',$w); } }
